### ISSUE TITLE
I have problem to build my startup.m

### ISSUE THREAD

**Issue by markofan** [fordanic/image-registration#1]
Sorry to bother you, I want use it to registration with demons for 3D MRI data. Can you give me a example of how to use it?

**Comment by fordanic** [comment]
Sure, to run the registration with demons simply launch it with the following command:
[deformed, displacementField, displacementFieldInverse] = run_non_rigid_registration(moving, fixed, 'demons', 'add', 3, 0, [10], true, [1.5], true, [1.5])
with moving and fixed set to the data volumes to be registered.
