### ISSUE TITLE
I want to know how to load the fixed and moving image?

### ISSUE THREAD

**Issue by markofan** [fordanic/image-registration#2]

**Comment by fordanic** [comment]
Load image data into MATLAB using any of the available methods to load data. Then assign the data to fixed and moving. For example:
load mri
im = double(squeeze(D));
moving = im;

**Comment by markofan** [comment]
First Thank you sooo much! You are so sweet! But I still want to know what is the format of your image? Should I change in to .mat or I can use the .img?

**Comment by fordanic** [comment]
Format on disk doesn't matter.
