### ISSUE TITLE
I am so sorry! But I still have trouble

### ISSUE THREAD

**Issue by markofan** [fordanic/image-registration#3]
this is my startup file
addpath('path-to-this-repository')
setup_image_registration_repository();

load ('NORMA_002_S_0295.mat')
im = double(squeeze(D));
moving = im;

fixed=load('template_041_S_0898.mat')
im1 = double(squeeze(D));
fixed = im1;

[deformed, displacementField, displacementFieldInverse] = run_non_rigid_registration(moving, fixed, 'demons', 'add', 3, 0, [10], true, [1.5], true, [1.5])

But it is wrong!
here are the mistake:
Image size is too small for this resampling factor. No resampling.
Image size is too small for this resampling factor. No resampling.
Error using add_update_field_to_acc_field (line 53)
Unknown accumulation method

Error in registration_execute (line 365)
                    registration.displacementField =
                    add_update_field_to_acc_field(...

Error in run_non_rigid_registration (line 178)
    registration_execute();

Error in startup (line 35)
[deformed, displacementField, displacementFieldInverse] =
run_non_rigid_registration(moving, fixed, 'demons', 'add', 3, 0,
[10], true, [1.5], true, [1.5])

Sorry!

**Comment by markofan** [comment]
my data is 206*176*170

**Comment by markofan** [comment]
my data is stored in .mat. It is 3  dimension. The size of it is 206  176  170

**Comment by markofan** [comment]
I have soved the load problem, 
but Error using add_update_field_to_acc_field (line 53)
Unknown accumulation method  ----I dont know how to solv it 
when I change a accumulation method  
the code run successfully!

**Comment by fordanic** [comment]
Two things, my mistake, it should be sum and not add as parameter. The start scale need to be set in accordance with data size, so probably 2 as start scale should work.

**Comment by markofan** [comment]
Thank you!
I have solved my problem!
You write a wonderful code! I feel so ashamed for asking you all the time without thinking by myself!
I should read your code carefully and try to understand it!
You are such a nice guy, I should learn more from you!
