### ISSUE TITLE
Something strange happen!

### ISSUE THREAD

**Issue by markofan** [fordanic/image-registration#4]
Yesterday I ran the code successfully! But today the code have a error
I just put  [deformed, displacementField, displacementFieldInverse] = run_non_rigid_registration(moving, fixed, 'demons', 'sum', 2, 0, [10], true, [1.5], true, [1.5])

then the error
Error using CUDA_non_rigid_registration3d (line 65)
CUDA_affine_registration3d is implemented as a mex-file. It has
not been compiled on this platform.

Error in run_non_rigid_registration (line 132)
        [deformed, displacementField{1}, displacementField{2},
        displacementField{3}] = ...

I did add dforsberg-cuda-7a242e0d5a4c and dforsberg-matlab_cuda-7877e5d85f5f toolboxes

I dont know why

**Comment by markofan** [comment]
It is driving me crazy I have changed nothing! It just cant work

**Comment by markofan** [comment]
I use MATLAB, do I have to install CUDA Toolkit. But yesterday, I just ran successfully, Strange！

**Comment by fordanic** [comment]
So yesterday I assume you didn't have my CUDA stuff downloaded. Note that the CUDA stuff doesn't not support all bells and whistles as found in the CPU code and only adds computational performance to a limited subset of functionality. Additionally, you have to build the whole thing. I'd suggest to remove them from the path and run again. 

Also, I'd suggest you have a look at the registration_example_3D file to see how to set parameters and to run a registration that runs on the CPU.

**Comment by markofan** [comment]
Thank you so much, I just remove the GPU part, and everything is OK! 
I am a student in China. Maybe I am too offensive. Do you use Wechat? Can we be Wechat friends?
I am sorry but I just want learn more from you 
my wechat number 1123899128
if you dont want, It is OK.  I will always remember your help
Thank you so much!

**Comment by fordanic** [comment]
Glad I could help and that people find my stuff useful.

**Comment by markofan** [comment]
I am in Shanghai now. If you come to Shanghai, or any place in China. Please tell me. I can be your tourist guide, I  am Sincerely.  you really help me a lot
