### ISSUE TITLE
hi when you get the displacementfield, how to get the deformed data?

### ISSUE THREAD

**Issue by markofan** [fordanic/image-registration#5]
I use demons for my registration on 3D data, I get a displacementfield which has 3 matrix, so it is simply add the displacementfield with moving, or it has some complex method. I see the function ba_interp3, but I can't understand it.
sorry to bother you! Thank you!

**Comment by fordanic** [comment]
To displace/transform/deform an image (preferably the moving image) with a given displacement field, use:
```matlab
deformedInput = deformation(input, displacementField, interpolation)
```
The three matrices, or actually cells, contains the X, Y and Z components respectively of the full displacement field.
